### ISSUE TITLE
No module named: "fcntl"

### ISSUE THREAD

**Issue by mjones57575757** [Evidlo/remarkable_keyboard#7]
Here is my issue and I have no idea how to fix it:

PS C:\Users\mason> pip install remarkable-keyboard
Requirement already satisfied: remarkable-keyboard in c:\users\mason\miniconda3\lib\site-packages (4.0.0)
Requirement already satisfied: paramiko in c:\users\mason\miniconda3\lib\site-packages (from remarkable-keyboard) (3.4.0)
Requirement already satisfied: pycryptodome in c:\users\mason\miniconda3\lib\site-packages (from remarkable-keyboard) (3.20.0)
Requirement already satisfied: pynput in c:\users\mason\miniconda3\lib\site-packages (from remarkable-keyboard) (1.7.6)
Requirement already satisfied: remarkable-mouse>=5 in c:\users\mason\miniconda3\lib\site-packages (from remarkable-keyboard) (7.1.1)
Requirement already satisfied: screeninfo in c:\users\mason\miniconda3\lib\site-packages (from remarkable-keyboard) (0.8.1)
Requirement already satisfied: sortedcontainers in c:\users\mason\miniconda3\lib\site-packages (from remarkable-keyboard) (2.4.0)
Requirement already satisfied: libevdev in c:\users\mason\miniconda3\lib\site-packages (from remarkable-mouse>=5->remarkable-keyboard) (0.11)
Requirement already satisfied: bcrypt>=3.2 in c:\users\mason\miniconda3\lib\site-packages (from paramiko->remarkable-keyboard) (4.1.2)
Requirement already satisfied: cryptography>=3.3 in c:\users\mason\miniconda3\lib\site-packages (from paramiko->remarkable-keyboard) (41.0.7)
Requirement already satisfied: pynacl>=1.5 in c:\users\mason\miniconda3\lib\site-packages (from paramiko->remarkable-keyboard) (1.5.0)
Requirement already satisfied: six in c:\users\mason\miniconda3\lib\site-packages (from pynput->remarkable-keyboard) (1.16.0)
Requirement already satisfied: cffi>=1.12 in c:\users\mason\miniconda3\lib\site-packages (from cryptography>=3.3->paramiko->remarkable-keyboard) (1.16.0)
Requirement already satisfied: pycparser in c:\users\mason\miniconda3\lib\site-packages (from cffi>=1.12->cryptography>=3.3->paramiko->remarkable-keyboard) (2.21)
PS C:\Users\mason> rekeyboard
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mason\miniconda3\Scripts\rekeyboard.exe\__main__.py", line 4, in <module>
  File "C:\Users\mason\miniconda3\Lib\site-packages\remarkable_keyboard\remarkable_keyboard.py", line 16, in <module>
    from remarkable_keyboard.mappings import KeyboardMapping
  File "C:\Users\mason\miniconda3\Lib\site-packages\remarkable_keyboard\mappings.py", line 4, in <module>
    from pynput._util.xorg import X11Error
  File "C:\Users\mason\miniconda3\Lib\site-packages\pynput\_util\xorg.py", line 44, in <module>
    _check_and_initialize()
  File "C:\Users\mason\miniconda3\Lib\site-packages\pynput\_util\xorg.py", line 39, in _check_and_initialize
    display = Xlib.display.Display()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mason\miniconda3\Lib\site-packages\Xlib\display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mason\miniconda3\Lib\site-packages\Xlib\display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "C:\Users\mason\miniconda3\Lib\site-packages\Xlib\protocol\display.py", line 85, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mason\miniconda3\Lib\site-packages\Xlib\support\connect.py", line 72, in get_display
    mod = _relative_import(modname)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mason\miniconda3\Lib\site-packages\Xlib\support\connect.py", line 55, in _relative_import
    return importlib.import_module('..' + modname, __name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mason\miniconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mason\miniconda3\Lib\site-packages\Xlib\support\unix_connect.py", line 31, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

Please help me

**Comment by Evidlo** [comment]
Try the most recent version (4.0.1).  It should fix the issue
